#!/usr/bin/env python3
#
# __SHORT_DESC__
#
import os
import sys
import coloredlogs, logging

log = logging
global args


def main():
    global log
    coloredlogs.install(
        level=args.logging_level,
        fmt="%(asctime)s,%(msecs)03d %(programname)s[%(process)d] %(levelname)s %(message)s",
    )
    log.info("TODO")


if __name__ == "__main__":
    import argparse

    global args
    parser = argparse.ArgumentParser(description="TODO: short descrpition")
    parser.add_argument(
        "--debug",
        dest="logging_level",
        action="store_const",
        const=logging.DEBUG,
        default=logging.INFO,
        help="write debugging output in the log",
    )
    parser.add_argument(
        "--info",
        dest="logging_level",
        action="store_const",
        const=logging.INFO,
        help="write informational output in the log",
    )
    args = parser.parse_args()
    main()
