# Set for your hardware
CHIP = esp32
BOARD = node32s

# Compile options
BUILD_EXTRA_FLAGS += -DDEBUG
#BUILD_EXTRA_FLAGS += -DMUTILA_DEBUG
#BUILD_EXTRA_FLAGS += -DDEBUG_OUTPUT=Serial

# Supported speeds: 921600 460800 230400 115200 57600 9600
UPLOAD_SPEED = 921600

# Turn on to see compiler warnings and such
#VERBOSE = 1

include ../esp.mk

